/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvVHJhbnNjZW5kL0pFUy9QUk9KRUNUUy9hbmd1bGFyMi11ZGVteS1jb3Vyc2UvYW1vcy10ZXN0aW5nLXByb2plY3Qvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Wb2x1bWVzL1RyYW5zY2VuZC9KRVMvUFJPSkVDVFMvYW5ndWxhcjItdWRlbXktY291cnNlL2Ftb3MtdGVzdGluZy1wcm9qZWN0L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
